"""empty message

Revision ID: 62b38aa25201
Revises: b8b163a5bf4d
Create Date: 2020-08-01 11:35:51.072998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b38aa25201'
down_revision = 'b8b163a5bf4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guideline', sa.Column('code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guideline', 'code')
    # ### end Alembic commands ###
